#!/bin/bash

echo "
##############################################################################
# This script has been deprecated, please use the version provided as part of
# the wmf-sre-laptop package:
#
# https://wikitech.wikimedia.org/wiki/Wmf-sre-laptop
##############################################################################
"
exit 1
